"""Module 5 - add daily_check, weekly_check, defect activity types

Adds three new ActivityType values so the SATS Dashboard can offer
dedicated "Daily Check", "Weekly Check" and "Defect" tiles/pages,
alongside the already-existing Transit Check (transit_inspection) and
Carry Forward (carry_forward_maintenance) types, which now get their own
dedicated dashboard tiles / list pages as well (no schema change needed
for those two - they already exist as values on this enum).

Revision ID: 6b595f6ff038
Revises: c7f3a9b1d2e4
Create Date: 2026-08-12 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6b595f6ff038"
down_revision = "c7f3a9b1d2e4"
branch_labels = None
depends_on = None

OLD_VALUES = (
    "aircraft_inspection", "technical_inspection", "transit_inspection", "flight_inspection",
    "maintenance", "replacement", "fixing_rectification", "wheel_change", "tsr", "mic",
    "quality_inspection_ri", "scheduled_maintenance", "unscheduled_maintenance",
    "carry_forward_maintenance", "other",
)

NEW_VALUES = OLD_VALUES + ("daily_check", "weekly_check", "defect")


def upgrade():
    bind = op.get_bind()

    if bind.dialect.name == "postgresql":
        # PostgreSQL supports adding values to an existing enum type
        # directly (no rows need to change, no rebuild required).
        for value in ("daily_check", "weekly_check", "defect"):
            op.execute(f"ALTER TYPE activity_type ADD VALUE IF NOT EXISTS '{value}'")
    else:
        # SQLite (and other dialects without native enum support) store
        # the column as VARCHAR with a CHECK constraint generated by
        # SQLAlchemy's Enum type - use batch mode to swap it out.
        with op.batch_alter_table("activities") as batch_op:
            batch_op.alter_column(
                "activity_type",
                existing_type=sa.Enum(*OLD_VALUES, name="activity_type"),
                type_=sa.Enum(*NEW_VALUES, name="activity_type"),
                existing_nullable=False,
            )


def downgrade():
    bind = op.get_bind()

    if bind.dialect.name == "postgresql":
        connection = op.get_bind()
        # Move any rows using the new values back to "other" before the
        # type is rebuilt without them (Postgres cannot drop enum values).
        for value in ("daily_check", "weekly_check", "defect"):
            connection.execute(
                sa.text("UPDATE activities SET activity_type = 'other' WHERE activity_type = :v"),
                {"v": value},
            )

        op.execute("ALTER TYPE activity_type RENAME TO activity_type_old")
        old_enum = sa.Enum(*OLD_VALUES, name="activity_type")
        old_enum.create(connection)
        op.execute(
            "ALTER TABLE activities ALTER COLUMN activity_type TYPE activity_type "
            "USING activity_type::text::activity_type"
        )
        op.execute("DROP TYPE activity_type_old")
    else:
        with op.batch_alter_table("activities") as batch_op:
            batch_op.alter_column(
                "activity_type",
                existing_type=sa.Enum(*NEW_VALUES, name="activity_type"),
                type_=sa.Enum(*OLD_VALUES, name="activity_type"),
                existing_nullable=False,
            )
