"""Module 5: add categories table for admin-managed taxonomy

Revision ID: 8d8e7b181a16
Revises: a1b2c3d4e5f6
Create Date: 2026-08-11 05:43:03.497883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8e7b181a16'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.Enum('ACTIVITY_TYPE', 'MAINTENANCE_TYPE', 'TSR_CATEGORY', 'MIC_CATEGORY', 'RI_CATEGORY', name='category_group'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group', 'name', name='uq_category_group_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_group'), ['group'], unique=False)
        batch_op.create_index('ix_categories_group_active', ['group', 'is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('ix_categories_group_active')
        batch_op.drop_index(batch_op.f('ix_categories_group'))

    op.drop_table('categories')
    # ### end Alembic commands ###
