"""Initial schema: users, stations, shifts, aircraft, airlines, activities, notifications, audit_logs

Revision ID: fb88ee4f90bc
Revises: 
Create Date: 2026-08-10 23:53:11.549874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb88ee4f90bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iata_code', sa.String(length=5), nullable=True),
    sa.Column('icao_code', sa.String(length=5), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('airlines', schema=None) as batch_op:
        batch_op.create_index('ix_airlines_active', ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_airlines_iata_code'), ['iata_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_airlines_icao_code'), ['icao_code'], unique=True)

    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index('ix_stations_active', ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_stations_code'), ['code'], unique=True)

    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=20), nullable=False),
    sa.Column('aircraft_type', sa.String(length=100), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('PIA', 'THIRD_PARTY', name='aircraft_category'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.create_index('ix_aircraft_active', ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_airline_id'), ['airline_id'], unique=False)
        batch_op.create_index('ix_aircraft_category', ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_registration'), ['registration'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'DCE', 'SHIFT_INCHARGE', 'ENGINEER', name='user_role'), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index('ix_users_role_active', ['role', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_station_id'), ['station_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'is_read'], unique=False)

    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('ALPHA', 'BETA', 'CHARLIE', 'DELTA', name='shift_name'), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('shift_incharge_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shift_incharge_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'station_id', name='uq_shift_name_station')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_shift_incharge_id'), ['shift_incharge_id'], unique=False)
        batch_op.create_index('ix_shifts_station_active', ['station_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_shifts_station_id'), ['station_id'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.Column('logged_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='activity_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['logged_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_aircraft_id'), ['aircraft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_logged_by_id'), ['logged_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_station_id'), ['station_id'], unique=False)
        batch_op.create_index('ix_activities_station_status', ['station_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_status'))
        batch_op.drop_index('ix_activities_station_status')
        batch_op.drop_index(batch_op.f('ix_activities_station_id'))
        batch_op.drop_index(batch_op.f('ix_activities_shift_id'))
        batch_op.drop_index(batch_op.f('ix_activities_logged_by_id'))
        batch_op.drop_index(batch_op.f('ix_activities_aircraft_id'))

    op.drop_table('activities')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_station_id'))
        batch_op.drop_index('ix_shifts_station_active')
        batch_op.drop_index(batch_op.f('ix_shifts_shift_incharge_id'))

    op.drop_table('shifts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_station_id'))
        batch_op.drop_index('ix_users_role_active')
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_employee_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aircraft_registration'))
        batch_op.drop_index('ix_aircraft_category')
        batch_op.drop_index(batch_op.f('ix_aircraft_airline_id'))
        batch_op.drop_index('ix_aircraft_active')

    op.drop_table('aircraft')
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_code'))
        batch_op.drop_index('ix_stations_active')

    op.drop_table('stations')
    with op.batch_alter_table('airlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airlines_icao_code'))
        batch_op.drop_index(batch_op.f('ix_airlines_iata_code'))
        batch_op.drop_index('ix_airlines_active')

    op.drop_table('airlines')
    # ### end Alembic commands ###
